name: Keep Supabase Awake (Test)

on:
  schedule:
    # Every 10 minutes
    - cron: "0 10 * * 1,4"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: curl -s "https://dquwhuppqjgqqkkneohc.supabase.co/rest/v1/?apikey=${{ secrets.SUPABASE_KEY }}"
