name: Keep Supabase Awake (Test)

on:
  schedule:
    # Every 10 minutes
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: curl -s "https://dquwhuppqjgqqkkneohc.supabase.co/rest/v1/?apikey=${{ secrets.SUPABASE_KEY }}"
